### ISSUE TITLE
Need improvements

### ISSUE THREAD

**Issue by Thecave3** [vpacik/atom-language-root#2]
I've added the package and tried to open  ROOT file but i can't see any syntax highlighter or any other kind of language support. Can you help me by at least improve the package documentation or the README.md?

**Comment by vpacik** [comment]
Hi @Thecave3. Thank you for your interest in this feature.

Since the ROOT syntax is overlapping with (OOP) C++ language to vast extend, it needs a delicate treatment and thus the package is still under development and not yet (by far) in a desired shape. You will now once the progress is made.

**Comment by Thecave3** [comment]
Thank you for your work. I appreciate the answer and your works. Can't wait to use ROOT on atom.

**Comment by vpacik** [comment]
So instead of implementing most of the grammar from scratch, I found more elegant way by injecting additional ROOT-specific rules into a standard (build-in/core) C++ language. Now the highlighting should be consistent with a C/C++ standards which is a reasonable starting point (snippets, etc. will come later). I published the new version few moments ago, so you can update and use it. And of course please feel free to let me know if you find something (mis-)behaving unexpectedly.
